qsub velbertRun73.sh
qsub velbertRun74.sh 
qsub velbertRun75.sh 
qsub velbertRun76.sh 
qsub velbertRun77.sh 
qsub velbertRun78.sh 
qsub velbertRun79.sh 
qsub velbertRun80.sh 
qsub velbertRun81.sh 
qsub velbertRun82.sh 
qsub velbertRun83.sh 
qsub velbertRun84.sh 
qsub velbertRun85.sh 
qsub velbertRun86.sh 
qsub velbertRun87.sh 
qsub velbertRun88.sh 
qsub velbertRun89.sh 
qsub velbertRun90.sh 
qsub velbertRun91.sh 
qsub velbertRun92.sh 
qsub velbertRun93.sh 
qsub velbertRun94.sh 
qsub velbertRun95.sh 
qsub velbertRun96.sh 
